### ISSUE TITLE
Domaci_ukol_01_statistika - odevzdání

### ISSUE THREAD

**Issue by JanaEsther** [JanaEsther/Domaci_ukol_01_statistika#1]
@honzahes

Ahoj Honzo,
mám hotový domácí úkol. Prosím, podívej se na to. Díky moc, Jana

**Comment by JanaEsther** [comment]
@honzahes
Ahoj Honzo, můžeš se prosím podívat, jestli je to takto v pořádku? Díky moc.

**Comment by honzahes** [comment]
Ahoj, takhle je to uplne idealni :)
